Repository codeit-sprint-fullstack/8-sprint-mission-fe, pull requests merged in 2025-10, with the labels that each got.

#132 [이광체] sprint8
  .github/pull-request-template.md
  .github/workflows/auto-label-assign.yml
  .gitignore
  README.md
  eslint.config.mjs
  jsconfig.json
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  public/file.svg
  public/globe.svg
  public/images/icon/ic_arrow_down.svg
  public/images/icon/ic_heart.svg
  public/images/icon/ic_kebab.svg
  public/images/icon/ic_medal.svg
  public/images/icon/ic_profile.svg
  public/images/logo.svg
  public/images/sample/img_sample1.png
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/(article)/article/[id]/page.jsx
  src/app/(article)/article/edit/[id]/page.jsx
  src/app/(article)/article/edit/page.jsx
  src/app/(article)/article/page.jsx
  src/app/(article)/layout.jsx
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.js
  src/app/page.js
  src/app/providers.jsx
  src/components/ArticleDetailSection.jsx
  src/components/BestItem.jsx
  src/components/BestSection.jsx
  src/components/Button.jsx
  src/components/Button.module.css
  src/components/CommentSection.jsx
  src/components/DropdownMenu.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/Layout.jsx
  src/components/PostItem.jsx
  src/components/PostSection.jsx
  src/components/SearchAndSort.jsx
  src/components/pages/ArticleDetailPage.jsx
  src/components/pages/ArticleEditPage.jsx
  src/components/pages/ArticlePage.jsx
  src/components/pages/HomePage.jsx
  src/lib/articleApi.js
  src/lib/commentApi.js
  src/providers/ArticleProvider.jsx
  src/providers/CommentProvider.jsx
Labels: 순한맛🐑, 최종 제출

#137 [나주현] srpint8
  .gitignore
  .prettierignore
  .prettierrc
  db.json
  eslint.config.mjs
  jsconfig.json
  next.config.mjs
  package-lock.json
  package.json
  postcss.config.mjs
  public/file.svg
  public/fonts/Pretendard-Black.otf
  public/fonts/Pretendard-Bold.otf
  public/fonts/Pretendard-ExtraBold.otf
  public/fonts/Pretendard-ExtraLight.otf
  public/fonts/Pretendard-Light.otf
  public/fonts/Pretendard-Medium.otf
  public/fonts/Pretendard-Regular.otf
  public/fonts/Pretendard-SemiBold.otf
  public/fonts/Pretendard-Thin.otf
  public/fonts/ROKAFSansBold.otf
  public/fonts/ROKAFSansBold.woff2
  public/fonts/ROKAFSansMedium.otf
  public/fonts/ROKAFSansMedium.woff2
  public/globe.svg
  public/icons/facebook.svg
  public/icons/instagram.svg
  public/icons/x.svg
  public/icons/youtube.svg
  public/logos/PandaLogo.svg
  public/next.svg
  public/vercel.svg
  public/window.svg
  src/app/discussion/page.jsx
  src/app/favicon.ico
  src/app/globals.css
  src/app/layout.jsx
  src/app/page.jsx
  src/components/shared/Footer.jsx
  src/components/shared/Footer.module.css
  src/components/shared/Header.jsx
  src/components/shared/Header.module.css
  src/components/shared/atoms/Button.jsx
  src/components/shared/atoms/Button.module.css
  src/components/shared/atoms/Logo.jsx
  src/components/shared/atoms/Logo.module.css
  src/components/shared/molecules/SnsLinks.jsx
  src/components/shared/molecules/SnsLinks.module.css
  tailwind.config.js
Labels: 진행 중 🏃

#145 [조원정] sprint 9
  8-sprint-fe/next.config.mjs
  8-sprint-fe/public/btn_visibility_off_24px.svg
  8-sprint-fe/public/btn_visibility_on_24px.svg
  8-sprint-fe/public/ic_google.svg
  8-sprint-fe/public/ic_kakao.svg
  8-sprint-fe/src/api/fetchClient.js
  8-sprint-fe/src/api/fetchProducts.js
  8-sprint-fe/src/api/userService.js
  8-sprint-fe/src/app/(auth)/_components/LoginPage.jsx
  8-sprint-fe/src/app/(auth)/_components/SignUpPage.jsx
  8-sprint-fe/src/app/(auth)/_components/validator.js
  8-sprint-fe/src/app/(auth)/layout.jsx
  8-sprint-fe/src/app/(auth)/login/page.jsx
  8-sprint-fe/src/app/(auth)/signup/page.jsx
  8-sprint-fe/src/app/(components)/Header.jsx
  8-sprint-fe/src/app/(components)/Layout.jsx
  8-sprint-fe/src/app/(components)/Nav.jsx
  8-sprint-fe/src/app/(components)/atoms/Logo.jsx
  8-sprint-fe/src/app/(components)/atoms/OAuth.jsx
  8-sprint-fe/src/app/(components)/atoms/PasswordInput.jsx
  8-sprint-fe/src/app/(components)/atoms/TextInput.jsx
  8-sprint-fe/src/app/(contents)/board/[id]/page.jsx
  8-sprint-fe/src/app/(contents)/board/[id]/patch/page.jsx
  8-sprint-fe/src/app/(contents)/board/_components/ArticleForm.jsx
  8-sprint-fe/src/app/(contents)/board/_components/BoardDetailPage.jsx
  8-sprint-fe/src/app/(contents)/board/_components/BoardPage.jsx
  8-sprint-fe/src/app/(contents)/board/_components/BoardPatchPage.jsx
  8-sprint-fe/src/app/(contents)/board/_components/BoardPostPage.jsx
  8-sprint-fe/src/app/(contents)/board/_components/Card.jsx
  8-sprint-fe/src/app/(contents)/board/_components/CommentList.jsx
  8-sprint-fe/src/app/(contents)/board/_components/ImageBox.jsx
  8-sprint-fe/src/app/(contents)/board/_components/ListCommunity.jsx
  8-sprint-fe/src/app/(contents)/board/page.jsx
  8-sprint-fe/src/app/(contents)/board/post/page.jsx
  8-sprint-fe/src/app/(contents)/items/[id]/page.jsx
  8-sprint-fe/src/app/(contents)/items/_components/BestProducts.jsx
  8-sprint-fe/src/app/(contents)/items/_components/ItemDetailPage.jsx
  8-sprint-fe/src/app/(contents)/items/_components/ItemsPage.jsx
  8-sprint-fe/src/app/(contents)/items/_components/ProductItem.jsx
  8-sprint-fe/src/app/(contents)/items/_components/ProductsList.jsx
  8-sprint-fe/src/app/(contents)/items/page.jsx
  8-sprint-fe/src/app/(contents)/layout.jsx
  8-sprint-fe/src/app/globals.css
  8-sprint-fe/src/app/layout.jsx
  8-sprint-fe/src/app/page.jsx
  8-sprint-fe/src/providers/AuthProvider.jsx
Labels: 미완성🫠, 최종 제출
