Repository codeit-sprint-fullstack/8-sprint-mission-fe, pull requests merged in 2025-08, with the labels that each got.

#57 [황채원] Sprint 4
  .github/.gitconfig
  .github/README.md
  .github/mercurial.ini
  .github/pull-request-template.md
  README.md
  js/js-request/ArticleService.js
  js/js-request/ProductService.js
  js/js-request/main.js
  js/js-request/package.json
Labels: 매운맛🔥, 최종 제출

#78 [홍명주] Sprint 4
  js/ArticleService.js
  js/ProductService.js
  js/main.js
  package.json
  test.html
Labels: 최종 제출

#75 [민기범] Sprint4
  .prettierrc
  js/ArticleService.js
  js/ProductService.js
  js/formUtils.js
  js/main.js
  login/index.html
  login/login.js
  signup/index.html
  signup/signup.js
Labels: 매운맛🔥, 최종 제출

#62 [김동영] Sprint 4
  scripts/apis/ArticleService.js
  scripts/apis/ProductService.js
  scripts/apis/main.js
Labels: 매운맛🔥, 최종 제출

#65 [나주현] Sprint4
  .gitignore
  CSS/login.css
  JS/ArticleService.js
  JS/ProductService.js
  JS/common.js
  JS/login.js
  JS/main.js
  README.md
  login.html
  package-lock.json
  package.json
  signup.html
Labels: 매운맛🔥, 최종 제출

#67 [원치준] sprint4
  Img/sprint4_getArticleList.png
  scripts/ArticleService.js
  scripts/ProductService.js
  scripts/main.js
Labels: 최종 제출

#88 [이유찬] Sprint 5
  .gitignore
  eslint.config.js
  index.html
  package-lock.json
  package.json
  src/api/ArticleService.js
  src/api/ProductService.js
  src/api/request.js
  src/components/DropDown/DropDown.jsx
  src/components/DropDown/DropDown.module.scss
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.scss
  src/components/Header/Header.jsx
  src/components/Header/Header.module.scss
  src/components/Header/Logo/Logo.jsx
  src/components/Header/Logo/Logo.module.scss
  src/components/Header/Navigator/Navigator.jsx
  src/components/Header/Navigator/Navigator.module.scss
  src/components/PageButton/PageButton.jsx
  src/components/PageButton/PageButton.module.scss
  src/components/ProductList/ProductItem/ProductItem.jsx
  src/components/ProductList/ProductItem/ProductItem.module.scss
  src/components/ProductList/ProductList.jsx
  src/components/ProductList/ProductList.module.scss
  src/components/ProductList/ProductListController/ProductListController.jsx
  src/components/ProductList/ProductListController/ProductListController.module.scss
  src/hooks/useResponsive.jsx
  src/images/ic_arrow_down.svg
  src/images/ic_arrow_left.svg
  src/images/ic_facebook.svg
  src/images/ic_heart.svg
  src/images/ic_instagram.svg
  src/images/ic_pandamarket.svg
  src/images/ic_search.svg
  src/images/ic_twitter.svg
  src/images/ic_youtube.svg
  src/main.jsx
  src/pages/Home.jsx
  src/styles/_mixin.scss
  src/styles/_variables.scss
  src/styles/reset.css
  src/styles/style.scss
  vite.config.js
Labels: 매운맛🔥, 최종 제출

#91 [김연만]sprint-5
  gitignore
  package-lock.json
  package.json
  public/images/ic_facebook.svg
  public/images/ic_instagram.svg
  public/images/ic_search.svg
  public/images/ic_twitter.svg
  public/images/ic_youtude.svg
  public/images/panda.svg
  public/index.html
  src/App.js
  src/components/BestProducts.js
  src/components/Footer.js
  src/components/Header.js
  src/components/Pagination.js
  src/components/ProductCard.js
  src/components/ProductGrid.js
  src/components/SearchBar.js
  src/components/SortDropdown.js
  src/hooks/useProducts.js
  src/index.css
  src/index.js
  src/pages/MarketPage.js
  src/services/productService.js
Labels: 최종 제출

#93 [조성민] sprint5
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/api/api.js
  src/assets/arrowLeft.svg
  src/assets/arrowRight.svg
  src/assets/facebook.svg
  src/assets/heart.svg
  src/assets/instagram.svg
  src/assets/page1.svg
  src/assets/page1Active.svg
  src/assets/page2.svg
  src/assets/page2Active.svg
  src/assets/page3.svg
  src/assets/page3Active.svg
  src/assets/page4.svg
  src/assets/page4Active.svg
  src/assets/page5.svg
  src/assets/page5Active.svg
  src/assets/panda.svg
  src/assets/search.svg
  src/assets/twitter.svg
  src/assets/youtube.svg
  src/components/BestProductList.jsx
  src/components/BestProducts.jsx
  src/components/Footer.jsx
  src/components/Header.jsx
  src/components/SaleProducts.jsx
  src/main.jsx
  src/styles/Common.module.css
  src/styles/Footer.css
  src/styles/Global.css
  src/styles/Header.css
  vite.config.js
Labels: 최종 제출

#85 [황채원] Sprint 5
  .github/.gitignore/.gitconfig
  .github/.gitignore/mercurial.ini
  .gitignore
  README.md
  package-lock.json
  package.json
  public/index.html
  src/API/ArticleService.js
  src/API/ProductService.js
  src/API/request.js
  src/Components/App.jsx
  src/Components/DropDown/DropDown.jsx
  src/Components/DropDown/DropDown.module.css
  src/Components/DropDown/ic_DownArrow.svg
  src/Components/Footer/Footer.jsx
  src/Components/Footer/Footer.module.css
  src/Components/Footer/images/ic_YouTube.svg
  src/Components/Footer/images/ic_facebook.svg
  src/Components/Footer/images/ic_instagram.svg
  src/Components/Footer/images/ic_twitter.svg
  src/Components/Header/Header.jsx
  src/Components/Header/Header.module.css
  src/Components/Header/Logo/Logo.module.css
  src/Components/Header/Logo/logo.jsx
  src/Components/Header/Logo/logo_img.svg
  src/Components/Header/Navigator/Nav.jsx
  src/Components/Header/Navigator/Navigator.module.css
  src/Components/PageButton/PageButton.jsx
  src/Components/PageButton/PageButton.module.css
  src/Components/PageButton/ic_PageButton_left.svg
  src/Components/PageButton/ic_PageButton_right.svg
  src/Components/ProductList/BestProductList/BestProductList.jsx
  src/Components/ProductList/BestProductList/BestProductList.module.css
  src/Components/ProductList/ProductCard/ProductCard.jsx
  src/Components/ProductList/ProductCard/ProductCard.module.css
  src/Components/ProductList/ProductCard/ic_heart.svg
  src/Components/ProductList/ProductList.jsx
  src/Components/ProductList/ProductList.module.css
  src/Components/ProductList/ProductListController/ProductListController.jsx
  src/Components/ProductList/ProductListController/ProductListController.module.css
  src/Components/ProductList/ProductListController/ic_search.svg
  src/index.js
  src/style/color_variables.css
  src/style/reset.css
  src/style/style.css
Labels: 매운맛🔥, 최종 제출

#87 [원치준] sprint5
  .gitignore
  eslint.config.js
  index.html
  package-lock.json
  package.json
  src/App.jsx
  src/assets/footer_facebook.png
  src/assets/footer_instagram.png
  src/assets/footer_twitter.png
  src/assets/footer_youtube.png
  src/assets/header_panda.png
  src/assets/sprint5_page.png
  src/components/cardItemList.jsx
  src/components/footer.jsx
  src/components/header.jsx
  src/css/app.css
  src/css/cardItemList.css
  src/css/footer.css
  src/css/header.css
  src/hooks/useProducts.js
  src/hooks/useResponsivePageSize.js
  src/main.jsx
  src/pages/MarketPage.jsx
  vite.config.js
Labels: 최종 제출

#112 [이광체] sprint6
  README.md
  src/App.js
  src/components/Header.js
  src/components/Header.module.css
  src/components/Items/ItemList.js
  src/components/Items/ItemList.module.css
  src/components/Items/ItemListSelling.js
  src/components/Items/ItemListSelling.module.css
  src/components/Items/ProductCard.js
  src/components/auth/AuthHeader.js
  src/components/auth/AuthHeader.module.css
  src/components/auth/LoginForm.js
  src/components/auth/LoginForm.module.css
  src/components/auth/SignupForm.js
  src/components/auth/SignupForm.module.css
  src/components/auth/SocialLogin.js
  src/components/auth/SocialLogin.module.css
  src/components/home/Banner.module.css
  src/components/home/BannerBottom.js
  src/components/home/BannerTop.js
  src/components/home/HotItem.js
  src/components/home/HotItem.module.css
  src/components/registration/RegistrationForm.js
  src/components/registration/RegistrationForm.module.css
  src/components/registration/RegistrationInput.js
  src/components/registration/RegistrationInput.module.css
  src/components/registration/RegistrationTag.js
  src/components/registration/RegistrationTag.module.css
  src/components/registration/RegistrationTagSection.js
  src/components/registration/RegistrationTagSection.module.css
  src/pages/Home.js
  src/pages/Items.js
  src/pages/Login.js
  src/pages/Registration.js
  src/pages/Signup.js
  src/utils/useAuthInputCheck.js
  src/utils/useRegistrationInputCheck.js
Labels: 매운맛🔥, 최종 제출

#121 [김성은] sprint6
  panda-market-react/CHANGELOG.md
  panda-market-react/public/components/atoms/close-btn.svg
  panda-market-react/src/App.jsx
  panda-market-react/src/api/client.js
  panda-market-react/src/api/productsApi.js
  panda-market-react/src/components/atoms/Tag.jsx
  panda-market-react/src/components/molecules/FeatureItem.jsx
  panda-market-react/src/components/molecules/ProductCard.jsx
  panda-market-react/src/components/molecules/TextBanner.jsx
  panda-market-react/src/components/molecules/TextInput.jsx
  panda-market-react/src/components/molecules/Textarea.jsx
  panda-market-react/src/components/organisms/Header.jsx
  panda-market-react/src/lib/constants/errorMessages.js
  panda-market-react/src/lib/hooks/useProducts.js
  panda-market-react/src/lib/hooks/useRegistrationFormValidation.js
  panda-market-react/src/lib/utils/validator.js
  panda-market-react/src/lib/validation/productResponse.guard.js
  panda-market-react/src/pages/MainPage.jsx
  panda-market-react/src/pages/ProductListPage.jsx
  panda-market-react/src/pages/RegistrationPage.jsx
  panda-market-react/src/styles/common.css
  panda-market-react/src/styles/components/atoms/Tag.module.css
  panda-market-react/src/styles/components/molecules/FeatureItem.module.css
  panda-market-react/src/styles/components/molecules/TextBanner.module.css
  panda-market-react/src/styles/components/molecules/TextInput.module.css
  panda-market-react/src/styles/components/molecules/Textarea.module.css
  panda-market-react/src/styles/pages/MainPage.module.css
  panda-market-react/src/styles/pages/ProductListPage.module.css
  panda-market-react/src/styles/pages/RegistrationPage.module.css
  panda-market-react/src/styles/reset.css
Labels: 순한맛🐑, 최종 제출
