Repository codeit-sprint-fullstack/8-sprint-mission-fe, pull requests merged in 2025-07, with the labels that each got.

#7 [이광체] sprint1&2
  README.md
  css/index.css
  css/login-signup.css
  css/reset.css
  font/ROKAF Sans Bold.otf
  font/ROKAF Sans Medium.otf
  font/ROKAF Slab Serif Bold.otf
  font/ROKAF Slab Serif Medium.otf
  img/Img_home_01.png
  img/Img_home_02.png
  img/Img_home_03.png
  img/Img_home_bottom.png
  img/Img_home_top.png
  img/btn_visibility_on.png
  img/ic_facebook.png
  img/ic_google.png
  img/ic_google@2x.png
  img/ic_google@3x.png
  img/ic_instagram.png
  img/ic_kakao.png
  img/ic_kakao@2x.png
  img/ic_kakao@3x.png
  img/ic_twitter.png
  img/ic_youtube.png
  img/panda-icon-2.png
  img/panda-icon.png
  index.html
  login/index.html
  signup/index.html
Labels: 매운맛🔥, 진행 중 🏃

#6 [황채원] Sprint 1 & 2
  faq.html
  img/eye-close.svg
  img/eye_open.svg
  img/home_bottom_img.svg
  img/home_img_01.svg
  img/home_img_03.svg
  img/home_ing_02.svg
  img/home_top_img.svg
  img/ic_Google.svg
  img/ic_Kakao.svg
  img/ic_YouTube.svg
  img/ic_facebook.svg
  img/ic_instargram.svg
  img/ic_twitter.svg
  img/logo_lg.svg
  img/logo_md.svg
  img/logo_sm.svg
  img/판다 얼굴.svg
  index.html
  items.html
  login.css
  login.html
  privacy.html
  reset.css
  signup.css
  signup.html
  style.css
Labels: 매운맛🔥, 최종 제출

#29 [황승찬] Sprint 1 & 2
  faq/index.html
  images/landing/buy_item.svg
  images/landing/facebook.svg
  images/landing/goods.svg
  images/landing/home_bottom.svg
  images/landing/home_top.svg
  images/landing/instagram.svg
  images/landing/logo.svg
  images/landing/sell_item.svg
  images/landing/twitter.svg
  images/landing/youtube.svg
  images/login/google.svg
  images/login/kakaotalk.svg
  images/login/pw_eye.svg
  index.html
  index/index.html
  items/index.html
  login/index.html
  login/style.css
  privacy/index.html
  reset.css
  signup/index.html
  signup/style.css
Labels: 매운맛🔥, 최종 제출

#36 [신민준] Sprint 3
  .DS_Store
  Mission2/README.md
  Mission2/global.css
  Mission2/global.css.map
  Mission2/global.scss
  Mission2/login/signup/style.css.map
  Mission2/login/style.css.map
  Mission2/privacy/privacy.html
  Mission2/styles/style.css
  Mission2/styles/style.css.map
  Mission2/styles/style.scss
  README.md
  faq/faq.html
  global.css
  global.css.map
  global.scss
  img/footer_codeit.svg
  img/footer_privacy.svg
  img/hiddenIcon.svg
  img/ic_facebook.svg
  img/ic_instagram.svg
  img/ic_twitter.svg
  img/ic_youtube.svg
  img/img_home_bottom.svg
  img/img_home_top.svg
  img/login_googleLogo.svg
  img/login_kakaoLogo.svg
  img/logoText.svg
  img/logo_title.svg
  img/pandaFace.svg
  img/pandaLogo_Face_Text.svg
  img/section1_img.svg
  img/section2_img.svg
  img/section3_img.svg
  index.html
  items/items.html
  login/.DS_Store
  login/login.html
  login/login.js
  login/style.css
  login/style.css.map
  login/style.scss
  package.json
  privacy/privacy.html
  signup/.DS_Store
  signup/signup.html
  signup/signup.js
  signup/style.css
  signup/style.css.map
  signup/style.scss
  style.css
  style.css.map
  style.scss
  validate/validate.css
  validate/validate.css.map
  validate/validate.js
  validate/verifyLogin.css
  validate/verifyLogin.css.map
  validate/verifyLogin.scss
Labels: 최종 제출

#46 [이광체] sprint3
  _headers
  css/global.css
  css/index.css
  css/login-signup.css
  css/reset.css
  img/banner/Img_home_01.png
  img/banner/Img_home_02.png
  img/banner/Img_home_03.png
  img/banner/Img_home_bottom.png
  img/banner/Img_home_top.png
  img/btn/btn_visibility_off_24px.svg
  img/btn/btn_visibility_on_24px.svg
  img/btn_visibility_on.png
  img/icon/ic_facebook.png
  img/icon/ic_google.png
  img/icon/ic_google@2x.png
  img/icon/ic_google@3x.png
  img/icon/ic_instagram.png
  img/icon/ic_kakao.png
  img/icon/ic_kakao@2x.png
  img/icon/ic_kakao@3x.png
  img/icon/ic_twitter.png
  img/icon/ic_youtube.png
  img/logo/panda-icon-2.png
  img/logo/panda-icon.png
  index.html
  items/index.html
  js/data/users.js
  js/logic/logIn-signup/DOM.js
  js/logic/logIn-signup/inputCheck.js
  js/logic/logIn-signup/logIn-signUp.js
  login/index.html
  signup/index.html
Labels: 매운맛🔥, 최종 제출

#52 [조원정] sprint 3
  README.md
  css/forms.css
  css/login_signup.css
  css/palette.css
  css/reset.css
  css/style.css
  font/pretendard.css
  images/btn_visibility_on_24px.svg
  images/icon/ic_facebook.svg
  images/icon/ic_google.svg
  images/icon/ic_instagram.svg
  images/icon/ic_kakao.svg
  images/icon/ic_panda.svg
  images/icon/ic_twitter.svg
  images/icon/ic_youtube.svg
  images/img_home/img_home_01.svg
  images/img_home/img_home_02.svg
  images/img_home/img_home_03.svg
  images/img_home/img_home_bottom.svg
  images/img_home/img_home_top.svg
  index.html
  js/USERDATA.js
  js/alert.js
  js/forms.js
  js/validation.js
  login/index.html
  signup/index.html
Labels: 매운맛🔥, 최종 제출

#51 [나주현] Sprint 3
  CSS/login.css
  CSS/style.css
  JS/common.js
  JS/login.js
  JS/signup.js
  README.md
  index.html
  login.html
  signup.html
Labels: 매운맛🔥, 최종 제출

#41 [곽민준] sprint 3
  panda/index.html
  panda/scripts/ArticleService.js
  panda/scripts/ProductService.js
  panda/scripts/main.js
Labels: 매운맛🔥, 최종 제출

#47 [원치준] Sprint 3
  Img/login_pand_face.png
  Img/pand_face.png
  Img/sprint3_alert.png
  Img/sprint3_login.png
  Img/sprint3_signup.png
  index.html
  login.html
  scripts/login.js
  scripts/signup.js
  scripts/utils.js
  signup.html
  style/style.css
Labels: 최종 제출

#50 [조성민] Sprint 3
  README.md
  assets/css/common.css
  assets/css/main.css
  assets/css/reset.css
  assets/images/bestitem.svg
  assets/images/eye(close).svg
  assets/images/eye(open).svg
  assets/images/facebook.svg
  assets/images/google.svg
  assets/images/instagram.svg
  assets/images/kakao.svg
  assets/images/logo.svg
  assets/images/panda-1.svg
  assets/images/panda-2.svg
  assets/images/panda-face.svg
  assets/images/register.svg
  assets/images/search.svg
  assets/images/twitter.svg
  assets/images/youtube.svg
  assets/js/common.js
  assets/js/login.js
  assets/js/signup.js
  index.html
  login.css
  login.html
  loginimg/logo.svg
  signup.css
  signup.html
Labels: 최종 제출

#54 [황승찬] Sprint3
  commonModule/loginSignup.js
  commonModule/platformScreenSet.js
  index.html
  login/index.html
  login/login.css
  reset.css
  signup/index.html
  signup/signup.css
Labels: 매운맛🔥, 최종 제출

#68 [김성은] sprint3
  README.md
  assets/css/auth.css
  assets/css/main.css
  assets/js/auth/auth.js
  assets/js/auth/dom.js
  assets/js/auth/handler.js
  assets/js/auth/popup.js
  assets/js/auth/ui.js
  assets/js/auth/validation.js
  index.html
  login/index.html
  signup/index.html
Labels: 순한맛🐑, 최종 제출
